git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - "4"
os:
  - linux
  - osx
env:
  global:
    - TARGET_ARCH=x64
osx_image: xcode7

matrix:
  include:
    - os: linux
      env: TARGET_ARCH=arm
    - os: linux
      env: TARGET_ARCH=ia32
  allow_failures:
    - os: osx

script: './script/cibuild'

branches:
  only:
    - master
